# Generated by Django 3.2.5 on 2022-02-04 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('a', 'Available'), ('o', 'On Loan'), ('h', 'On Hold')], default='a', help_text='Book Availabiliy', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(help_text='10 Character <a href="https://www.isbn-international.org/content/what-isbn">ISBN number</a>', max_length=10, unique=True, verbose_name='ISBN'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(max_length=30),
        ),
    ]
