# Generated by Django 3.2.5 on 2022-02-04 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20220204_0111'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loaner', models.CharField(max_length=50, null=True)),
                ('loaner_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('book_loaned', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='catalog.book')),
            ],
        ),
    ]
