# Generated by Django 3.2.5 on 2022-02-04 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_loaninstance'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('f', 'Fantasy'), ('R', 'Romance'), ('r', 'Realistic Fiction'), ('n', 'Non-fiction'), ('m', 'Mystery'), ('s', 'Sci-Fi'), ('t', 'Thriller')], default='f', help_text='Book Genre', max_length=1),
        ),
    ]
