# Generated by Django 3.2.5 on 2022-02-04 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('t', 'Thriller'), ('m', 'Mystery'), ('R', 'Romance'), ('n', 'Non-fiction'), ('r', 'Realistic Fiction'), ('s', 'Sci-Fi'), ('f', 'Fantasy')], default='f', help_text='Book Genre', max_length=1),
        ),
    ]
