# Generated by Django 3.2.5 on 2022-02-04 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('r', 'Realistic Fiction'), ('n', 'Non-fiction'), ('m', 'Mystery'), ('f', 'Fantasy'), ('s', 'Sci-Fi'), ('R', 'Romance'), ('t', 'Thriller')], default='f', help_text='Book Genre', max_length=1),
        ),
    ]
