# Generated by Django 3.2.5 on 2022-02-06 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0010_alter_book_genre'),
    ]

    operations = [
        migrations.AddField(
            model_name='loaninstance',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('R', 'Romance'), ('t', 'Thriller'), ('f', 'Fantasy'), ('m', 'Mystery'), ('s', 'Sci-Fi'), ('n', 'Non-fiction'), ('r', 'Realistic Fiction')], default='f', help_text='Book Genre', max_length=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
