# Generated by Django 3.2.5 on 2022-02-11 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_auto_20220206_0246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('n', 'Non-fiction'), ('R', 'Romance'), ('f', 'Fantasy'), ('s', 'Sci-Fi'), ('r', 'Realistic Fiction'), ('t', 'Thriller'), ('m', 'Mystery')], default='f', help_text='Book Genre', max_length=1),
        ),
    ]
