# Generated by Django 3.2.5 on 2022-03-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_alter_book_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('HORROR', 'Horror'), ('MYSTERY', 'Mystery'), ('FANTASY', 'Fantasy'), ('NON-FICTION', 'Non-fiction'), ('HISTORICAL FICTION', 'Historical Fiction'), ('SCIENCE FICTION', 'Science Fiction'), ('ADVENTURE', 'Adventure'), ('REALISTIC FICTION', 'Realistic Fiction')], help_text='Book Genre', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(blank=True, choices=[('AVAILABLE', 'Available'), ('ON LOAN', 'On Loan'), ('ON HOLD', 'On Hold')], default='Available', help_text='Book Availabiliy', max_length=30),
        ),
    ]
