# Generated by Django 3.2.5 on 2022-03-13 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_auto_20220302_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_overdue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(blank=True, choices=[('SCIENCE FICTION', 'Science Fiction'), ('MYSTERY', 'Mystery'), ('HORROR', 'Horror'), ('NON-FICTION', 'Non-fiction'), ('HISTORICAL FICTION', 'Historical Fiction'), ('REALISTIC FICTION', 'Realistic Fiction'), ('FANTASY', 'Fantasy'), ('ADVENTURE', 'Adventure')], help_text='Book Genre', max_length=30),
        ),
    ]
